wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.15
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1651417306
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 24
      4: 3.7.11
      5: 0.12.15
      8:
      - 5
batch_size:
  desc: null
  value: 16
learning_rate:
  desc: null
  value: 0.0001
